from pathlib import Path

BASE_DIR = Path(__file__).parent.parent.parent
MODEL_DIR = BASE_DIR / "stock_model"
PLOTS_DIR = BASE_DIR / "plots"
DATA_OUT_DIR = BASE_DIR / "data_prep_output" / "stock"

MAX_SEQ_LENGTH = 256
CONTEXT = 60
HORIZON = 1
UPDATE_INTERVAL = 60
RETRAIN_EVERY = 60
INITIAL_PERIOD = "7d"
INITIAL_INTERVAL = "1m"
LIVE_INTERVAL = "1m"
LIVE_PERIOD = "2h"

TOKEN_PAD = 103
TOKEN_SEP = 102
TOKEN_START = 101
VOCAB_SIZE = 104
VALUE_RANGE = 101

D_MODEL = 128
N_HEAD = 4
N_LAYER = 6
D_FF = 512
DROPOUT = 0.1

BATCH_SIZE = 32
LEARNING_RATE = 1e-3
WEIGHT_DECAY = 0.01
MAX_EPOCHS = 20
EARLY_STOP_PATIENCE = 5
GRAD_CLIP = 1.0
FP16 = True
TEMPERATURE = 0.7
N_GENERATIONS = 3

TRAIN_SPLIT = 0.8
RANDOM_SEED = 42
